query pageQuery {
  ...LayoutQueryFragment
}

query contentQuery($relativePath: String!) {
  ...LayoutQueryFragment
  page(relativePath: $relativePath) {
    ...PageParts
  }
}

query programQuery($relativePath: String!) {
  ...LayoutQueryFragment
  program(relativePath: $relativePath) {
    ...ProgramParts
  }
}
